import Vue from 'vue';
import { Popover, Button,MessageBox,Message,Pagination,Radio,Select,Option} from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
Vue.use(Message);
Vue.use(Pagination);
Vue.use(Radio);
Vue.use(Select);
Vue.use(Option);
Vue.use(Popover);
Vue.use(Button);
Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;